import UserFlow
import Navigable

open UserFlow

def kindName : Kind → String
  | .start => "start"
  | .screen => "screen"
  | .decision => "decision"
  | .action => "action"
  | .outcome => "outcome"

def quote (s : String) : String :=
  "\"" ++ ((s.replace "\\" "\\\\").replace "\"" "\\\"") ++ "\""

def gdscript : String := Id.run do
  let mut out := "# SPDX-License-Identifier: MIT\n# Copyright (c) 2026 K. S. Ernest (iFire) Lee\n"
  out := out ++ "# Generated by tests/user_flow (lake exe user_flow gdscript): edit UserFlow.lean, not this file.\n"
  out := out ++ "extends RefCounted\n\nconst NODES := {\n"
  for n in all do
    let (k, label, rx) := info n
    out := out ++ s!"\t{quote (nameOf n)}: \{\"kind\": {quote (kindName k)}, \"label\": {quote label}, \"rx\": {quote rx}},\n"
  out := out ++ "}\n\nconst EDGES := [\n"
  for (a, b, why) in edges do
    out := out ++ s!"\t[{quote (nameOf a)}, {quote (nameOf b)}, {quote why}],\n"
  return out ++ "]\n"

/-- Every rx scene the flow cites exists; a planted path must read as missing. -/
def check (root : System.FilePath) : IO UInt32 := do
  if ← (root / "addons/vsk_ui/flow/never_there.tscn").pathExists then
    IO.println "FAIL: a planted path reads as present"
    return 1
  let mut missing := 0
  let mut covered := 0
  let mut screens := 0
  for n in all do
    let (k, _, rx) := info n
    if k != .outcome then screens := screens + 1
    if rx != "" then
      if ← (root / rx.replace "res://" "").pathExists then
        if k != .outcome then covered := covered + 1
      else
        IO.println s!"MISSING {nameOf n}: {rx}"
        missing := missing + 1
  IO.println s!"user flow: {all.length} nodes, {edges.length} edges; rx covers {covered} of {screens} non-outcome nodes; {missing} cited scenes missing"
  for n in all do
    let (k, _, rx) := info n
    if k != .outcome && rx == "" then IO.println s!"  not yet in rx: {nameOf n}"
  let results ← Navigable.certify edges
  let mut failed := 0
  let mut atL0 := 0
  for (_, lvl, t) in results do
    if Navigable.found t then
      if lvl == 0 then atL0 := atL0 + 1
    else
      IO.println s!"NOT NAVIGABLE {t.query}: {repr t.outcome}"
      failed := failed + 1
  IO.println s!"witnesses: {results.length - failed} of {results.length} found ({atL0} at L0, the rest at L1)"
  -- Controls: an orphaned screen and a dead-end screen must each come back with no witness.
  let (_, _, orphan) ← Navigable.run (edges.filter (·.2.1 != .camera)) (Navigable.fromLaunch .camera)
  let (_, _, deadEnd) ← Navigable.run (edges.filter (·.1 != .camera)) (Navigable.toOutcome .camera)
  if Navigable.found orphan || Navigable.found deadEnd then
    IO.println "FAIL: a planted orphan or dead end still found a witness"
    return 1
  IO.println s!"controls: orphan {repr orphan.outcome}, dead end {repr deadEnd.outcome}"
  return if missing > 0 || failed > 0 then 1 else 0

def routes : IO UInt32 := do
  for n in all do
    let (path, lvl, _) ← Navigable.run edges (Navigable.fromLaunch n)
    IO.println s!"L{lvl} {nameOf n}: {" → ".intercalate (path.map nameOf)}"
  return 0

def main (args : List String) : IO UInt32 := do
  match args with
  | ["gdscript"] => IO.print gdscript; return 0
  | ["check", root] => check root
  | ["routes"] => routes
  | _ => IO.eprintln "usage: user_flow gdscript | check <rx root> | routes"; return 2
